# Generated by Django 5.0.6 on 2024-05-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('teacher', models.CharField(max_length=40, verbose_name='مدرس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('time', models.IntegerField(verbose_name='مدت زمان')),
                ('score', models.CharField(choices=[('1', '۱'), ('2', '۲'), ('3', '۳'), ('4', '۴'), ('5', '۵')], max_length=20, verbose_name='امتیاز')),
                ('level', models.CharField(choices=[('beginner', 'مقدمات'), ('intermediate', 'متوسط'), ('professional', 'پیشرفته')], max_length=20, verbose_name='سطح')),
                ('class_number', models.IntegerField(verbose_name='تعداد جلسات')),
                ('image_path', models.CharField(max_length=30, verbose_name='آدرس عکس')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'db_table': 'course',
            },
        ),
    ]
