# Generated by Django 5.0.6 on 2024-05-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('family', models.CharField(max_length=40, verbose_name='نام خانوادگی')),
                ('password', models.CharField(max_length=30, verbose_name='رمز عبور')),
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='شماره تلفن')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='ایمیل')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('certificate', models.CharField(choices=[('diploma', 'دیپلم'), ('bachelor', 'کارشناسی'), ('master', 'ارشد'), ('phd', 'دکترا')], max_length=15, verbose_name='تحصیلات')),
                ('profile_image', models.CharField(default='nophoto.png', max_length=20, verbose_name='عکس')),
                ('slug', models.SlugField()),
                ('courses', models.ManyToManyField(to='course.course', verbose_name='دوره\u200cها')),
            ],
            options={
                'verbose_name': 'پروقایل',
                'verbose_name_plural': 'پروفایل\u200cها',
                'db_table': 'profile',
            },
        ),
    ]
